# Generated by Django 4.2.1 on 2023-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('has_additional_guarantee', models.BooleanField(default=False)),
            ],
        ),
    ]
